[options]
admin_passwd = 12345
db_host = false
db_port = 5432
db_user = odoo17
db_password = 123456789
xmlrpc_port = 8070
logfile = /var/log/odoo17/vms.log
addons_path = /opt/odoo17/odoo17/addons,/opt/odoo17/vms
db_name = vms_db
workers = 2
max_cron_threads = 1
